### ISSUE TITLE
Image field in Workflows -> Send An Email (Version 1.8)

### ISSUE THREAD

**Issue by Sir-Starr** [benschi11/Rimango.ImageField#12]
This might not be a bug at all but possibly, in part, my lack of a more holistic knowledge of Orchard and its underlying technologies. With that said, and please bare with me, here is my short but annoying issue.

I am using the ImageField in a form that allows the user to upload an image. Once submitted I process that form via Orchard's Workflows to send an email to the owner of the website. In the Send An Email Component I add the following to the body in order to display the image in the email, <img src="http://www.vinpro.co.za/{Content.Fields.AskAnExpertForm.Image}" alt="" />.

Here is where the problem comes in. The image field outputs the following text
~/Media/Default/AskAnExpertForm/Image/temp.jpg 

As you can see there is a "~" at the start of the content and that causes the url in the href to not display the image as it is not a valid url.

My question is, how do I remove the "~" part of the field's content. I have tried a number of the "Tokens for Text Strings" on {Content.Fields.AskAnExpertForm.Image} but none of them outputs anything when I do this.

Please let me know if there is a solution that I am not seeing, or know of, or if you can somehow amend the ImageField when used as a Token in the Workflows.

Thank you.

Sean

**Comment by Devqon** [comment]
It probably has something to do with lines 210-214 of ImageFieldDriver.cs:

    // don't convert the url to ~/ if it's a fully qualified
    // as it might be stored on a remote storage (cdn, blob, ...)
        field.FileName = VirtualPathUtility.IsAbsolute(uploadedFileName)
            ? VirtualPathUtility.ToAppRelative(uploadedFileName)
            : uploadedFileName;

**Comment by Sir-Starr** [comment]
Thanks @Devqon, looking into that. Can I just edit that file and upload it? I am having difficulty with the website using any changes I have made. Would I need to restart the webserver if I do make changes? That might be a problem as the website is hosted on a server that I do not have much control over.

**Comment by Devqon** [comment]
Yes you can just edit any file without restarting the webserver. Orchard picks up any changes made to a file and then tries to dynamically recompile it, so you don't have to restart the website.

**Comment by benschi11** [comment]
Hi! That will be one way to do it. 
But can you try this: {Content.Fields.AskAnExpertForm.Image.FileName.Absolute}
when Image is the ImageField. Otherwise I would prefer to write my own Token - I can do that for if the ".Absolute" token is not working.

**Comment by Sir-Starr** [comment]
Thanks @Devqon I still cannot seem to do anything to that file.

@benschi11 I have tried your solution but it now returns no value for that field in the email.

**Comment by benschi11** [comment]
Ok, maybe try {Content.Fields.AskAnExpertForm.Image.Absolute} ?
I will investigate this problem when I am home and I hope I can provide you a solution (most likely I will implement an own tokenprovider for the ImageField)

**Comment by benschi11** [comment]
I added a new TokenProvider to the ImageField Version 1.8.1 or 1.9.1 (depending on your Orchard Version) - https://github.com/benschi11/Rimango.ImageField/releases.
Now {Content.Fields.AskAnExpertForm.Image.FileName.Absolute} should work just fine. Otherwise plz report any bugs.

**Comment by Starrzan** [comment]
@benschi11 That worked mighty fine! Thanks and thanks for the great module. A much needed one at that.
