### ISSUE TITLE
Bug in dimension calculation for user cropped image

### ISSUE THREAD

**Issue by flew2bits** [benschi11/Rimango.ImageField#13]
When an image is uploaded and cropped, the width and height are stored with the original aspect ratio rather than the aspect ratio of the cropped image. For example, I have an image that was cropped to 653x653, with a display size of 250x250, but the width and height were stored in the database as 250x142 which is the same aspect ratio of the original image with size 1920x1088.

**Comment by benschi11** [comment]
Thank you for the bug report. I hope I will find time to check this at the weekend.
