### ISSUE TITLE
Zero dimensions with high resolution pictures

### ISSUE THREAD

**Issue by gerloss** [benschi11/Rimango.ImageField#14]
When using the UserCrop settings I have encountered a bug where uploading high resolution images (over 2000px*3000px) causes the crop dialog to be bigger then the preset maximum dialog dimensions.

I have found that in these cases after setting the src of the image in reader.loadend both img.width and img.height are 0 despite reader.result properly containing the DataURL. This causes the calculatePreviewDimension function to fail in sizing the cropper dialog window.

I work around this issue by putting the code from reader.loadend into img.onload as in:

``` javascript
reader.onloadend = function () {
    img.src = reader.result;
};
img.onload = function() {
     //remaning code moved here from reader.loadend
}
```

This way the img.width and img.height are correctly loaded and the origDimensions object's Width and Height properties are set correctly.

**Comment by benschi11** [comment]
Thanks for the report. I will add your changes as soon as I find time or you can make an pull-request.
