### ISSUE TITLE
Upgrade to work with Orchard 1.10.x

### ISSUE THREAD

**Issue by rtpHarry** [benschi11/Rimango.ImageField#20]
I've forked your repo and made a new branch which has been upgraded to be compatible with 1.10.x.

https://github.com/rtpHarry/Rimango.ImageField/tree/v1.10

I'm also continuing my work on this to fix bugs and make small improvements as it seems a great solution for blogging featured images.

I don't think I can propose a PR that would create a new branch on your repo. Let me know if you want to create one and I'll to a PR to merge it over.

**Comment by benschi11** [comment]
Thank you for your great work! Currently I am very bussy and have no time left. But I will created a new branch 1.10.x for all the work thats need to be done for 1.10.x.
Please leave all your Bufixes on the develop branch.

**Comment by benschi11** [comment]
Thank you for the PullRequest!
